create table Seniors_WRL (
	rank INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	id  INT,
	gender VARCHAR(50),
	nation VARCHAR(50)
);
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (1, 'Sylvan', 'Norris', 3393, 'M', 'Japan');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (2, 'Filberto', 'Stubbings', 1896, 'M', 'Germany');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (3, 'Keenan', 'Bapty', 3719, 'M', 'Brazil');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (4, 'Petronilla', 'Mateuszczyk', 3857, 'F', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (5, 'Kellen', 'Gellett', 3306, 'M', 'Brazil');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (6, 'Udale', 'Bestman', 3917, 'M', 'Russia');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (7, 'Stephi', 'Lindup', 4147, 'F', 'Thailand');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (8, 'Madelon', 'Pettigrew', 35, 'F', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (9, 'Quintus', 'Furnival', 1545, 'M', 'Botswana');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (10, 'Rod', 'Sirey', 755, 'M', 'Oman');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (11, 'Selene', 'Jeffress', 945, 'F', 'France');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (12, 'Theodoric', 'Aaron', 1353, 'M', 'Venezuela');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (13, 'Kizzie', 'Dabes', 997, 'F', 'New Zealand');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (14, 'Peadar', 'Shipway', 3443, 'M', 'Mexico');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (15, 'Raye', 'Measen', 1939, 'F', 'Egypt');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (16, 'Joeann', 'Loughhead', 4515, 'F', 'Portugal');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (17, 'Mattias', 'Toynbee', 4996, 'M', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (18, 'Skipton', 'Kinmond', 3645, 'M', 'Australia');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (19, 'Gayle', 'Toffolini', 1023, 'F', 'Kazakhstan');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (20, 'Paloma', 'Tilburn', 3042, 'F', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (21, 'Ozzie', 'Gallehawk', 1650, 'M', 'Indonesia');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (22, 'Ingar', 'Blewitt', 3417, 'M', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (23, 'Aluino', 'Vickers', 2549, 'M', 'Russia');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (24, 'Carley', 'Blucher', 1130, 'F', 'Sierra Leone');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (25, 'Winn', 'Tremmil', 1265, 'M', 'Philippines');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (26, 'Katleen', 'Farey', 2788, 'F', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (27, 'Adam', 'Penritt', 4585, 'M', 'Russia');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (28, 'Moyna', 'Ickeringill', 1011, 'F', 'Panama');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (29, 'Leilah', 'Ducket', 2685, 'F', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (30, 'Oliy', 'Thiolier', 4629, 'F', 'Russia');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (31, 'Brandtr', 'Halstead', 2958, 'M', 'Poland');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (32, 'Elna', 'Daveley', 319, 'F', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (33, 'Gillie', 'Fitchell', 1959, 'F', 'France');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (34, 'Carlene', 'Hardan', 3064, 'F', 'Philippines');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (35, 'Alfonso', 'McIleen', 1118, 'M', 'Finland');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (36, 'Tori', 'Vigers', 3051, 'F', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (37, 'Kurtis', 'Cattemull', 3462, 'M', 'Indonesia');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (38, 'Daphene', 'Cuell', 1504, 'F', 'Sweden');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (39, 'Amity', 'Grimm', 1775, 'F', 'Botswana');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (40, 'Wildon', 'MacFall', 3351, 'M', 'Czech Republic');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (41, 'Sarajane', 'Johnsey', 4160, 'F', 'Brazil');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (42, 'Danna', 'Zellick', 1658, 'F', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (43, 'Dur', 'Preddle', 1863, 'M', 'Brazil');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (44, 'Alicea', 'Costelloe', 258, 'F', 'Portugal');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (45, 'Gilberto', 'Santostefano.', 4495, 'M', 'France');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (46, 'Haven', 'Risby', 3634, 'M', 'Honduras');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (47, 'Aretha', 'Shankle', 1135, 'F', 'Czech Republic');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (48, 'Sybille', 'Bowdler', 2013, 'F', 'Luxembourg');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (49, 'Doralin', 'Scholler', 3534, 'F', 'Indonesia');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (50, 'Nonah', 'Noni', 1920, 'F', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (51, 'Ashely', 'Farrimond', 4977, 'F', 'Angola');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (52, 'Jared', 'Karlowicz', 4333, 'M', 'Indonesia');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (53, 'Bucky', 'Pollett', 3735, 'M', 'Poland');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (54, 'Tomi', 'Faltskog', 1255, 'F', 'Ireland');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (55, 'Wilhelmine', 'Stuther', 2836, 'F', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (56, 'Margot', 'Mosey', 1461, 'F', 'Palestinian Territory');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (57, 'Wade', 'Cluckie', 4158, 'M', 'Brazil');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (58, 'Noreen', 'McMurty', 3711, 'F', 'Indonesia');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (59, 'Jenelle', 'Nyland', 2537, 'F', 'France');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (60, 'Garret', 'Balnaves', 3060, 'M', 'Japan');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (61, 'Niccolo', 'Ulyat', 428, 'M', 'Russia');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (62, 'Mord', 'Wyborn', 4072, 'M', 'Brazil');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (63, 'Elysia', 'Wodham', 1780, 'F', 'Albania');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (64, 'Ofelia', 'Amner', 271, 'F', 'Colombia');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (65, 'Gardiner', 'Dodd', 384, 'M', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (66, 'Piggy', 'Elleyne', 684, 'M', 'Brazil');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (67, 'Orrin', 'Medgewick', 4948, 'M', 'Cuba');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (68, 'Elna', 'Pingstone', 2918, 'F', 'Portugal');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (69, 'Sampson', 'Reolfo', 18, 'M', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (70, 'Franchot', 'Biagi', 4756, 'M', 'France');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (71, 'Zulema', 'Proffer', 4661, 'F', 'United States');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (72, 'Billie', 'Finnis', 3641, 'M', 'France');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (73, 'Roseanne', 'Sissons', 3631, 'F', 'Armenia');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (74, 'Solomon', 'Menendez', 1103, 'M', 'Brazil');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (75, 'Izak', 'Dulen', 3693, 'M', 'Russia');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (76, 'Kelwin', 'Phillipson', 1781, 'M', 'Croatia');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (77, 'Keenan', 'Mackett', 2687, 'M', 'Bangladesh');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (78, 'Tann', 'Blanshard', 2304, 'M', 'Ukraine');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (79, 'Osbourn', 'Cabbell', 465, 'M', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (80, 'Vilhelmina', 'Rappport', 4708, 'F', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (81, 'Inigo', 'Ghiraldi', 264, 'M', 'Yemen');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (82, 'Tierney', 'Moylan', 3186, 'F', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (83, 'Barbee', 'Gaskins', 348, 'F', 'Czech Republic');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (84, 'Vittorio', 'McGlew', 3175, 'M', 'Panama');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (85, 'Harman', 'Iannuzzelli', 4215, 'M', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (86, 'Caitlin', 'Abrey', 3171, 'F', 'Philippines');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (87, 'Karoly', 'Westrey', 2042, 'M', 'Ukraine');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (88, 'Dody', 'Gannan', 1094, 'F', 'Japan');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (89, 'Juliet', 'Greensmith', 2691, 'F', 'Philippines');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (90, 'Chevy', 'Grimbleby', 578, 'M', 'Nigeria');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (91, 'Fredra', 'Tomsen', 2357, 'F', 'Serbia');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (92, 'Tomlin', 'Groveham', 71, 'M', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (93, 'Margie', 'Hrinchishin', 3706, 'F', 'Ukraine');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (94, 'Olivie', 'Fivey', 1555, 'F', 'United States');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (95, 'Siobhan', 'Talby', 2972, 'F', 'Argentina');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (96, 'Betsy', 'Jowett', 2915, 'F', 'China');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (97, 'Benny', 'Mennell', 4466, 'M', 'Nigeria');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (98, 'Rochelle', 'Kearsley', 279, 'F', 'Indonesia');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (99, 'Michele', 'Fautley', 3860, 'F', 'Russia');
insert into Seniors_WRL (rank, first_name, last_name, id , gender, nation) values (100, 'Humberto', 'Poundesford', 2218, 'M', 'Portugal');
